[functions]
  external_node_modules = ["firebase-admin"]
  node_bundler = "esbuild"


[functions]
  directory = "netlify/functions"
  external_node_modules = ["firebase-admin"]
  node_bundler = "esbuild"
